### ISSUE TITLE
Add RingCentral to SCIM2 implementations

### ISSUE THREAD

**Issue by hauntingEcho** [erdtman/simplecloud.info#38]
I am AFK and can't open a pull request right now, but RingCentral implements SCIM2 and can be added to the list: https://developers.ringcentral.com/api-reference/SCIM/readUser2

**Comment by erdtman** [comment]
Yes, it looks like they have. Are you in any way affiliated with ringcentra?

**Comment by hauntingEcho** [comment]
Not particularly - I work with a customer of theirs who had been looking into using SCIM2.
