### ISSUE TITLE
Simplecloud.info is down

### ISSUE THREAD

**Issue by mooreds** [erdtman/simplecloud.info#69]
When I visit https://simplecloud.info I'm seeing a heroku error screen. Did this site get caught up in the 'heroku is no longer free' situation?

![image](https://github.com/erdtman/simplecloud.info/assets/91825/4e8cf2ba-bfc5-4204-a7ee-52292205a215)

**Comment by aaronpk** [comment]
Hi @erdtman, I'm not sure what happened to the domain, but it looks like it might have expired?

In the mean time, I registered https://scim.cloud and re-launched the site there. I would be happy to take over this repository and/or domain if you are no longer interested in maintaining it.

**Comment by erdtman** [comment]
Thanks for reporting, sorry for not having been more responsive

**Comment by erdtman** [comment]
step 1 done now available as a gh-pages https://erdtman.github.io/simplecloud.info/

will try to fix the DNS next
